server:
  port: ${APP_PORT:8080}
spring:
  application:
    name: tt-task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tt_task
    username: test
    password: ${DB_PG_PWD}
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: ${RABBITMQ_PWD}
    virtual-host: tt-host
services:
  user-service-url: http://localhost:8081
  team-service-url: http://localhost:8084
app:
  rabbitmq:
    queue-tasks: history.tasks-queue
    exchange: history-exchange